image: docker:latest

stages:
  - build
  - deploy

variables:
  CONTAINER_RU_IMAGE: registry.abbigli.com/abbigli/abbigli2-frontend/image:ru
  CONTAINER_COM_IMAGE: registry.abbigli.com/abbigli/abbigli2-frontend/image:com

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.abbigli.com

build_ru:
  stage: build
  script:
  - docker build --build-arg APP_ENV=prod-ru -t $CONTAINER_RU_IMAGE .
  - docker push $CONTAINER_RU_IMAGE
  only:
  - master

build_com:
  stage: build
  script:
  - docker build --build-arg APP_ENV=prod.env -t $CONTAINER_COM_IMAGE .
  - docker push $CONTAINER_COM_IMAGE
  only:
  - master

deploy_prod_ru:
  stage: deploy
  before_script:
  - apk add --no-cache openssh-client
  - mkdir -p ~/.ssh && chmod 700 ~/.ssh
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa.pub && chmod 600 ~/.ssh/id_rsa.pub
  - ssh-add ~/.ssh/id_rsa.pub
  - '[[ -f /.dockerenv ]] && echo "$SSH_SERVER_HOSTKEYS" > ~/.ssh/known_hosts'
  script:
  - ssh -t abbigli@abbigli.ru -p 811 "docker login registry.abbigli.com -u gitlab-ci-token -p $CI_BUILD_TOKEN && cd ~/deploy && docker-compose pull --ignore-pull-failures"
  - ssh -t abbigli@abbigli.ru -p 811 "docker exec -i nginx touch /etc/nginx/maintenance.front"
  - ssh -t abbigli@abbigli.ru -p 811 "cd ~/deploy && docker-compose up --no-deps -d app-frontend && docker exec -i app-frontend ash -c 'rm -rf /public/* && cp -r /app/public/* /public/'"
  - ssh -t abbigli@abbigli.ru -p 811 "docker exec -i nginx rm /etc/nginx/maintenance.front"
  environment:
    name: production_com
    url: https://abbigli.com
  when: manual
  only:
  - master

deploy_prod_com:
  stage: deploy
  before_script:
  - apk add --no-cache openssh-client
  - mkdir -p ~/.ssh && chmod 700 ~/.ssh
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa.pub && chmod 600 ~/.ssh/id_rsa.pub
  - ssh-add ~/.ssh/id_rsa.pub
  - '[[ -f /.dockerenv ]] && echo "$SSH_SERVER_HOSTKEYS" > ~/.ssh/known_hosts'
  script:
  - ssh -t abbigli@us2.abbigli.com -p 655 "docker login registry.abbigli.com -u gitlab-ci-token -p $CI_BUILD_TOKEN && cd ~/deploy && docker-compose pull --ignore-pull-failures"
  - ssh -t abbigli@us2.abbigli.com -p 655 "docker exec -i nginx touch /etc/nginx/maintenance.front"
  - ssh -t abbigli@us2.abbigli.com -p 655 "cd ~/deploy && docker-compose up --no-deps -d app-frontend && docker exec -i app-frontend ash -c 'rm -rf /public/* && cp -r /app/public/* /public/'"
  - ssh -t abbigli@us2.abbigli.com -p 655 "docker exec -i nginx rm /etc/nginx/maintenance.front"
  environment:
    name: production_com
    url: https://abbigli.com
  when: manual
  only:
  - master