image: docker:latest

stages:
  - build
  - deploy

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
  
build_alpha:
  stage: build
  script:
  - docker build --build-arg APP_ENV=alpha -t $CI_REGISTRY/$CI_PROJECT_PATH/alpha:$CI_COMMIT_SHA -t $CI_REGISTRY/$CI_PROJECT_PATH/alpha:latest .
  - docker push $CI_REGISTRY/$CI_PROJECT_PATH/alpha
  only:
  - develop

build_beta:
  stage: build
  script:
  - docker build --build-arg APP_ENV=beta -t $CI_REGISTRY/$CI_PROJECT_PATH/beta:$CI_COMMIT_SHA -t $CI_REGISTRY/$CI_PROJECT_PATH/beta:latest .
  - docker push $CI_REGISTRY/$CI_PROJECT_PATH/beta
  only:
  - staging
  
build_beta_ru:
  stage: build
  script:
  - docker build --build-arg APP_ENV=beta-ru -t $CI_REGISTRY/$CI_PROJECT_PATH/beta-ru:$CI_COMMIT_SHA -t $CI_REGISTRY/$CI_PROJECT_PATH/beta-ru:latest .
  - docker push $CI_REGISTRY/$CI_PROJECT_PATH/beta-ru
  only:
  - staging

build_ru:
  stage: build
  script:
  - docker build --build-arg APP_ENV=prod-ru -t $CI_REGISTRY/$CI_PROJECT_PATH/stable-ru:$CI_COMMIT_SHA -t $CI_REGISTRY/$CI_PROJECT_PATH/stable-ru:latest .
  - docker push $CI_REGISTRY/$CI_PROJECT_PATH/stable-ru
  only:
  - master

build_com:
  stage: build
  script:
  - docker build --build-arg APP_ENV=prod -t $CI_REGISTRY/$CI_PROJECT_PATH/stable:$CI_COMMIT_SHA -t $CI_REGISTRY/$CI_PROJECT_PATH/stable:latest .
  - docker push $CI_REGISTRY/$CI_PROJECT_PATH/stable
  only:
  - master
  
deploy_alpha:
  stage: deploy
  before_script:
  - apk add --no-cache openssh-client
  - mkdir -p ~/.ssh && chmod 700 ~/.ssh
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa.pub && chmod 600 ~/.ssh/id_rsa.pub
  - ssh-add ~/.ssh/id_rsa.pub
  - '[[ -f /.dockerenv ]] && echo "$SSH_SERVER_HOSTKEYS" > ~/.ssh/known_hosts'
  script:
  - ssh -t abbigli@de1.abbigli.com -p 799 "cd ./dev-server && ./deploy.sh -f --token=$CI_BUILD_TOKEN --env=app-frontend-alpha"
  environment:
    name: alpha
    url: http://alpha.abbigli.com
  when: manual
  only:
  - develop

deploy_beta:
  stage: deploy
  before_script:
  - apk add --no-cache openssh-client
  - mkdir -p ~/.ssh && chmod 700 ~/.ssh
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa.pub && chmod 600 ~/.ssh/id_rsa.pub
  - ssh-add ~/.ssh/id_rsa.pub
  - '[[ -f /.dockerenv ]] && echo "$SSH_SERVER_HOSTKEYS" > ~/.ssh/known_hosts'
  script:
  - ssh -t abbigli@de1.abbigli.com -p 799 "cd ./dev-server && ./deploy.sh -f --token=$CI_BUILD_TOKEN --env=app-frontend-beta"
  environment:
    name: beta
    url: http://beta.abbigli.com
  when: manual
  only:
  - staging
  
deploy_beta_ru:
  stage: deploy
  before_script:
  - apk add --no-cache openssh-client
  - mkdir -p ~/.ssh && chmod 700 ~/.ssh
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa.pub && chmod 600 ~/.ssh/id_rsa.pub
  - ssh-add ~/.ssh/id_rsa.pub
  - '[[ -f /.dockerenv ]] && echo "$SSH_SERVER_HOSTKEYS" > ~/.ssh/known_hosts'
  script:
  - ssh -t abbigli@de1.abbigli.com -p 799 "cd ./dev-server && ./deploy.sh -f --token=$CI_BUILD_TOKEN --env=app-frontend-beta-ru"
  environment:
    name: beta-ru
    url: http://beta.abbigli.ru
  when: manual
  only:
  - staging

deploy_prod_ru:
  stage: deploy
  before_script:
  - apk add --no-cache openssh-client
  - mkdir -p ~/.ssh && chmod 700 ~/.ssh
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa.pub && chmod 600 ~/.ssh/id_rsa.pub
  - ssh-add ~/.ssh/id_rsa.pub
  - '[[ -f /.dockerenv ]] && echo "$SSH_SERVER_HOSTKEYS" > ~/.ssh/known_hosts'
  script:
  - ssh -t abbigli@abbigli.ru -p 811 "docker login registry.abbigli.com -u gitlab-ci-token -p $CI_BUILD_TOKEN && cd ~/deploy && docker-compose pull --ignore-pull-failures app-frontend"
  - ssh -t abbigli@abbigli.ru -p 811 "docker exec -i nginx touch /etc/nginx/maintenance.front"
  - ssh -t abbigli@abbigli.ru -p 811 "cd ~/deploy && docker-compose up --no-deps -d app-frontend && docker exec -i app-frontend ash -c 'cp -r /app/public/* /public/'"
  - ssh -t abbigli@abbigli.ru -p 811 "docker exec -i nginx rm /etc/nginx/maintenance.front"
  environment:
    name: production/ru
    url: https://abbigli.ru
  when: manual
  only:
  - master

deploy_prod_com:
  stage: deploy
  before_script:
  - apk add --no-cache openssh-client
  - mkdir -p ~/.ssh && chmod 700 ~/.ssh
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa.pub && chmod 600 ~/.ssh/id_rsa.pub
  - ssh-add ~/.ssh/id_rsa.pub
  - '[[ -f /.dockerenv ]] && echo "$SSH_SERVER_HOSTKEYS" > ~/.ssh/known_hosts'
  script:
  - ssh -t abbigli@us2.abbigli.com -p 655 "docker login registry.abbigli.com -u gitlab-ci-token -p $CI_BUILD_TOKEN && cd ~/deploy && docker-compose pull --ignore-pull-failures app-frontend"
  - ssh -t abbigli@us2.abbigli.com -p 655 "docker exec -i nginx touch /etc/nginx/maintenance.front"
  - ssh -t abbigli@us2.abbigli.com -p 655 "cd ~/deploy && docker-compose up --no-deps -d app-frontend && docker exec -i app-frontend ash -c 'cp -r /app/public/* /public/'"
  - ssh -t abbigli@us2.abbigli.com -p 655 "docker exec -i nginx rm /etc/nginx/maintenance.front"
  environment:
    name: production/com
    url: https://abbigli.com
  when: manual
  only:
  - master