export const PROFILE_LOAD_REQUEST = 'profile/PROFILE_LOAD_REQUEST';
export const PROFILE_LOAD_RESPONSE = 'profile/PROFILE_LOAD_RESPONSE';

export const IMAGE_UPLOAD_REQUEST = 'profile/IMAGE_UPLOAD_REQUEST';
export const IMAGE_UPLOAD_RESPONSE = 'profile/IMAGE_UPLOAD_RESPONSE';

export const IMAGE_DELETE_REQUEST = 'profile/IMAGE_DELETE_REQUEST';
export const IMAGE_DELETE_RESPONSE = 'profile/IMAGE_DELETE_RESPONSE';

export const SAVE_CHANGES_REQUEST = 'profile/SAVE_CHANGES_REQUEST';
export const SAVE_CHANGES_RESPONSE = 'profile/SAVE_CHANGES_RESPONSE';
export const SAVE_CHANGES_ERROR = 'profile/SAVE_CHANGES_ERROR';

export const MORE_FOLLOWERS_REQUEST = 'profile/MORE_FOLLOWERS_REQUEST';
export const MORE_FOLLOWERS_RESPONSE = 'profile/MORE_FOLLOWERS_RESPONSE';
export const MORE_FOLLOWERS_ERROR = 'profile/MORE_FOLLOWERS_ERROR';

export const MORE_FOLLOWING_REQUEST = 'profile/MORE_FOLLOWING_REQUEST';
export const MORE_FOLLOWING_RESPONSE = 'profile/MORE_FOLLOWING_RESPONSE';
export const MORE_FOLLOWING_ERROR = 'profile/MORE_FOLLOWING_ERROR';
