export const PROFILE_LOAD_REQUEST = 'profile/PROFILE_LOAD_REQUEST';
export const PROFILE_LOAD_RESPONSE = 'profile/PROFILE_LOAD_RESPONSE';

export const IMAGE_UPLOAD_REQUEST = 'profile/IMAGE_UPLOAD_REQUEST';
export const IMAGE_UPLOAD_RESPONSE = 'profile/IMAGE_UPLOAD_RESPONSE';

export const IMAGE_DELETE_REQUEST = 'profile/IMAGE_DELETE_REQUEST';
export const IMAGE_DELETE_RESPONSE = 'profile/IMAGE_DELETE_RESPONSE';

export const SAVE_CHANGES_REQUEST = 'profile/SAVE_CHANGES_REQUEST';
export const SAVE_CHANGES_RESPONSE = 'profile/SAVE_CHANGES_RESPONSE';
export const SAVE_CHANGES_ERROR = 'profile/SAVE_CHANGES_ERROR';

export const ADD_CONTACT_REQUEST = 'profile/ADD_CONTACT_REQUEST';
export const ADD_CONTACT_RESPONSE = 'profile/ADD_CONTACT_RESPONSE';
export const ADD_CONTACT_ERROR = 'profile/ADD_CONTACT_ERROR';

export const DELETE_CONTACT_REQUEST = 'profile/DELETE_CONTACT_REQUEST';
export const DELETE_CONTACT_RESPONSE = 'profile/DELETE_CONTACT_RESPONSE';
export const DELETE_CONTACT_ERROR = 'profile/DELETE_CONTACT_ERROR';

export const PARTIAL_UPDATE_CONTACT_REQUEST =
'profile/PARTIAL_UPDATE_CONTACT_REQUEST';
export const PARTIAL_UPDATE_CONTACT_RESPONSE =
'profile/PARTIAL_UPDATE_CONTACT_RESPONSE';
export const PARTIAL_UPDATE_CONTACT_ERROR =
'profile/PARTIAL_UPDATE_CONTACT_ERROR';

export const MORE_FOLLOWERS_REQUEST = 'profile/MORE_FOLLOWERS_REQUEST';
export const MORE_FOLLOWERS_RESPONSE = 'profile/MORE_FOLLOWERS_RESPONSE';
export const MORE_FOLLOWERS_ERROR = 'profile/MORE_FOLLOWERS_ERROR';

export const MORE_FOLLOWING_REQUEST = 'profile/MORE_FOLLOWING_REQUEST';
export const MORE_FOLLOWING_RESPONSE = 'profile/MORE_FOLLOWING_RESPONSE';
export const MORE_FOLLOWING_ERROR = 'profile/MORE_FOLLOWING_ERROR';

export const CHANGE_FOLLOWING_STATUS = 'profile/CHANGE_FOLLOWING_STATUS';
export const FOLLOW_USER = 'profile/FOLLOW_USER';
export const UNFOLLOW_USER = 'profile/UNFOLLOW_USER';
